openapi: 3.0.0
info:
  title: Combined API Specification
  version: 1.0.0
paths:
  /health:
    get:
      summary: Health check endpoint
      description: Returns the health status of the service
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                type: string
  /{userId}:
    get:
      summary: Get user orders
      description: Retrieves all orders for a given user ID
      parameters:
      - name: userId
        in: path
        required: true
        description: The ID of the user
        schema:
          type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    orderId:
                      type: string
                      description: ID of the order
                    items:
                      type: array
                      items:
                        type: string
                        description: The item in the order
    post:
      summary: Create a new order
      description: Creates a new order for a given user ID
      parameters:
      - name: userId
        in: path
        required: true
        description: The ID of the user
        schema:
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                items:
                  type: array
                  items:
                    type: string
                    description: The item to order
      responses:
        '201':
          description: Order created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  orderId:
                    type: string
                    description: The ID of the order
        '400':
          description: Invalid request body
    delete:
      summary: Delete all orders for a user
      description: Deletes all orders associated with a specific user ID
      parameters:
      - name: userId
        in: path
        required: true
        description: The ID of the user
        schema:
          type: string
      responses:
        '204':
          description: Orders deleted successfully
        '404':
          description: User not found or no orders to delete
  /{userId}/{orderId}:
    delete:
      summary: Delete an order by ID
      description: Deletes a specific order by its ID for a given user
      parameters:
      - name: userId
        in: path
        required: true
        description: The ID of the user
        schema:
          type: string
      - name: orderId
        in: path
        required: true
        description: The ID of the order to delete
        schema:
          type: string
      responses:
        '204':
          description: Order deleted successfully
        '404':
          description: Order not found
components:
  schemas: {}
