openapi: 3.0.0
info:
  title: Combined API Specification
  version: 1.0.0
paths:
  /health:
    get:
      summary: Health check endpoint
      description: Returns the health status of the service
      responses:
        '200':
          description: Service is healthy
  /{userId}:
    get:
      summary: Get user orders
      description: Retrieves all orders for a specific user
      parameters:
      - name: userId
        in: path
        required: true
        description: The ID of the user
        schema:
          type: string
      responses:
        '200':
          description: Successful retrieval of user orders
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    orderId:
                      type: string
                      description: The ID of the order
                    items:
                      type: array
                      description: Array of items in the order
                      items:
                        type: string
    post:
      summary: Create a new order for a user
      description: Creates a new order for a given user
      parameters:
      - name: userId
        in: path
        required: true
        description: The ID of the user
        schema:
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                items:
                  type: array
                  description: Array of items in the order
                  items:
                    type: string
      responses:
        '201':
          description: Order created successfully
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
    delete:
      summary: Delete all orders for a user
      description: Deletes all orders associated with a specific user
      parameters:
      - name: userId
        in: path
        required: true
        description: The ID of the user
        schema:
          type: string
      responses:
        '204':
          description: Orders deleted successfully
        '404':
          description: User not found
        '500':
          description: Internal Server Error
  /{userId}/{orderId}:
    delete:
      summary: Delete a specific order for a user
      description: Deletes a single order identified by its ID for a given user
      parameters:
      - name: userId
        in: path
        required: true
        description: The ID of the user
        schema:
          type: string
      - name: orderId
        in: path
        required: true
        description: The ID of the order to delete
        schema:
          type: string
      responses:
        '204':
          description: Order deleted successfully
        '404':
          description: Order not found
        '500':
          description: Internal Server Error
components:
  schemas: {}
